### ISSUE TITLE
 java.lang.IllegalStateException: Task is already complete

### ISSUE THREAD

**Issue by pedrovarela86** [microg/android_external_GmsLib#9]
The app is crashing when Play services is not updates

I have on my `onCreate`

GoogleApiAvailability.getInstance().makeGooglePlayServicesAvailable(this);

the dialog appears.

Clicking outside the dialog, launches this exception. 

`03-03 16:55:55.073 17824-17824/com.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.demo, PID: 17824
                                                                              java.lang.IllegalStateException: Task is already complete
                                                                                  at com.google.android.gms.common.internal.zzac.zza(Unknown Source)
                                                                                  at com.google.android.gms.tasks.zzh.zzTG(Unknown Source)
                                                                                  at com.google.android.gms.tasks.zzh.setException(Unknown Source)
                                                                                  at com.google.android.gms.tasks.TaskCompletionSource.setException(Unknown Source)
                                                                                  at com.google.android.gms.internal.zzabj.zza(Unknown Source)
                                                                                  at com.google.android.gms.internal.zzaae.onCancel(Unknown Source)
                                                                                  at com.google.android.gms.common.SupportErrorDialogFragment.onCancel(Unknown Source)
                                                                                  at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1536)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:158)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by mribeiro** [comment]
Hi @pedrovarela86 ,
I'm having the same issue as well. Have you find a solução so far?

**Comment by pedrovarela86** [comment]
@mribeiro 

Yes I did. I completely give a turn around on that.  

Check my answer on Stackoverflow 

http://stackoverflow.com/a/42589636/3997720

I will appreciate your vote up.

**Comment by MIkeeJY** [comment]
java.lang.IllegalStateException: Task is already complete


07-18 15:52:41.762 E/AndroidRuntime( 1187): 	at com.google.android.gms.common.internal.zzac.zza(Unknown Source)


07-18 15:52:41.762 E/AndroidRuntime( 1187): 	at com.google.android.gms.tasks.zzh.zzTH(Unknown Source)


07-18 15:52:41.762 E/AndroidRuntime( 1187): 	at com.google.android.gms.tasks.zzh.setException(Unknown Source)


07-18 15:52:41.762 E/AndroidRuntime( 1187): 	at com.google.android.gms.tasks.TaskCompletionSource.setException(Unknown Source)


07-18 15:52:41.762 E/AndroidRuntime( 1187): 	at com.google.android.gms.internal.zzabj.zza(Unknown Source)


07-18 15:52:41.762 E/AndroidRuntime( 1187): 	at com.google.android.gms.internal.zzaae.onCancel(Unknown Source)


07-18 15:52:41.762 E/AndroidRuntime( 1187): 	at com.google.android.gms.common.SupportErrorDialogFragment.onCancel(Unknown Source)


07-18 15:52:41.762 E/AndroidRuntime( 1187): 	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1247)


07-18 15:52:41.762 E/AndroidRuntime( 1187): 	at android.os.Handler.dispatchMessage(Handler.java:107)


07-18 15:52:41.762 E/AndroidRuntime( 1187): 	at android.os.Looper.loop(Looper.java:194)


07-18 15:52:41.762 E/AndroidRuntime( 1187): 	at android.app.ActivityThread.main(ActivityThread.java:5427)


07-18 15:52:41.762 E/AndroidRuntime( 1187): 	at java.lang.reflect.Method.invokeNative(Native Method)


07-18 15:52:41.762 E/AndroidRuntime( 1187): 	at java.lang.reflect.Method.invoke(Method.java:525)


07-18 15:52:41.762 E/AndroidRuntime( 1187): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)


07-18 15:52:41.762 E/AndroidRuntime( 1187): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)


07-18 15:52:41.762 E/AndroidRuntime( 1187): 	at dalvik.system.NativeStart.main(Native Method)


Hi man，I also get this error in many machines which without google play services~
@pedrovarela86 @mribeiro

**Comment by MIkeeJY** [comment]
@pedrovarela86 @mribeiro   Finally,just upgrade to the latest version can solve this bug~
